version: '3.8'

services:
  # Zookeeper (required by Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
      - keycloak
      - opa
    ports:
      - "9092:9092"  # Internal listener
      - "9093:9093"  # External listener (for OAuth)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # OAuth Configuration
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: OAUTHBEARER
      KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: tech.goraft.kafka.oauthbearer.OAuthAuthenticateLoginCallbackHandler
      KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: tech.goraft.kafka.oauthbearer.OAuthAuthenticateValidatorCallbackHandler
      KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_JAAS_CONFIG: >
        org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
        OAUTH_LOGIN_SERVER='http://keycloak:8080/auth/realms/master/protocol/openid-connect'
        OAUTH_LOGIN_ENDPOINT='/token'
        OAUTH_LOGIN_GRANT_TYPE='client_credentials'
        OAUTH_CLIENT_ID='kafka_broker'
        OAUTH_CLIENT_SECRET='${KAFKA_BROKER_SECRET:-broker-secret}'
        OAUTH_INTROSPECT_SERVER='http://keycloak:8080/auth/realms/master/protocol/openid-connect'
        OAUTH_INTROSPECT_ENDPOINT='/token/introspect'
        OAUTH_ACCEPT_UNSECURE_SERVER='true';
      # OPA Authorization Configuration
      KAFKA_AUTHORIZER_CLASS_NAME: tech.goraft.kafka.opa.OpaAuthorizer
      KAFKA_OPA_AUTHORIZER_URL: http://opa:8181/v1/data/kafka/authz/allow
      KAFKA_OPA_AUTHORIZER_ALLOW_ON_ERROR: 'false'
      KAFKA_OPA_AUTHORIZER_CACHE_INITIAL_CAPACITY: '100'
      KAFKA_OPA_AUTHORIZER_CACHE_MAXIMUM_SIZE: '100'
      KAFKA_OPA_AUTHORIZER_CACHE_EXPIRE_AFTER_MS: '10000'
    volumes:
      - ./kafka-server.properties:/etc/kafka/server.properties:ro
      - ./custom-jars:/custom-jars  # For custom handler classes
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - kafka-network

  # Keycloak for OAuth2 Authentication
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: token-exchange
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/realm.json:ro
    networks:
      - kafka-network

  # Open Policy Agent for Authorization
  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    command: ["run", "--server", "--addr", ":8181", "/policies/policy.rego"]
    ports:
      - "8181:8181"
    volumes:
      - ./opa-policy.rego:/policies/policy.rego:ro
    networks:
      - kafka-network

  # Kafka UI (Optional - for management)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
      - keycloak
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: OAUTHBEARER
      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: >
        org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
        OAUTH_LOGIN_SERVER='http://keycloak:8080/auth/realms/master/protocol/openid-connect'
        OAUTH_LOGIN_ENDPOINT='/token'
        OAUTH_LOGIN_GRANT_TYPE='client_credentials'
        OAUTH_CLIENT_ID='kafka_ui'
        OAUTH_CLIENT_SECRET='${KAFKA_UI_SECRET:-ui-secret}'
        OAUTH_INTROSPECT_SERVER='http://keycloak:8080/auth/realms/master/protocol/openid-connect'
        OAUTH_INTROSPECT_ENDPOINT='/token/introspect'
        OAUTH_ACCEPT_UNSECURE_SERVER='true';
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge